Use hard-coded file names

diff --git a/.github/workflows/self-check.yml b/.github/workflows/self-check.yml
--- a/.github/workflows/self-check.yml
+++ b/.github/workflows/self-check.yml
@@ -26,7 +26,7 @@ jobs:
                   threshold_error: 0
             - name: Assert num_warnings == 0
               if: ${{ steps.fine.outputs.num_warnings != 0 }}
-              run: 'echo "::error ${{ steps.fine.inputs.root_file }}::num_warnings: ${{ steps.fine.outputs.num_warnings }}"; exit 1;'
+              run: 'echo "::error file=test/fine.tex::num_warnings: ${{ steps.fine.outputs.num_warnings }}"; exit 1;'
             - name: Lint bad.tex with no threshold set
               id: bad_no_threshold
               uses: ./
@@ -35,7 +35,7 @@ jobs:
                   working_directory: test/
             - name: Assert num_warnings > 0
               if: ${{ steps.bad_no_threshold.outputs.num_warnings <= 0 }}
-              run: 'echo "::error ${{ steps.bad_no_threshold.inputs.root_file }}::num_warnings: ${{ steps.bad_no_threshold.outputs.num_warnings }}"; exit 1;'
+              run: 'echo "::error file=test/bad.tex::num_warnings: ${{ steps.bad_no_threshold.outputs.num_warnings }}"; exit 1;'
             - name: Lint bad.tex with threshold set to known warnings
               id: bad_known_threshold
               uses: ./
@@ -45,7 +45,7 @@ jobs:
                   threshold_error: 21
             - name: Assert num_warnings <= 21
               if: ${{ steps.bad_known_threshold.outputs.num_warnings > 21 }}
-              run: 'echo "::error ${{ steps.bad_known_threshold.inputs.root_file }}::num_warnings: ${{ steps.bad_known_threshold.outputs.num_warnings }}"; exit 1;'
+              run: 'echo "::error file=test/bad.tex::num_warnings: ${{ steps.bad_known_threshold.outputs.num_warnings }}"; exit 1;'
             - name: Lint and spell-check fine.tex
               uses: ./
               id: fine_spell_check
@@ -56,7 +56,7 @@ jobs:
                   threshold_error: 1 # by default the word 'linter' will be unknown
             - name: Assert num_warnings == 1
               if: ${{ steps.fine_spell_check.outputs.num_warnings != 1 }}
-              run: 'echo "::error ${{ steps.fine_spell_check.inputs.root_file }}::num_warnings: ${{ steps.fine_spell_check.outputs.num_warnings }}"; exit 1;'
+              run: 'echo "::error file=test/fine.tex::num_warnings: ${{ steps.fine_spell_check.outputs.num_warnings }}"; exit 1;'
             - name: Lint and spell-check fine.tex
               id: fine_spell_check_w_dict
               uses: ./
@@ -67,4 +67,4 @@ jobs:
                   threshold_error: 0
             - name: Assert num_warnings == 0
               if: ${{ steps.fine_spell_check_w_dict.outputs.num_warnings != 0 }}
-              run: 'echo "::error ${{ steps.fine_spell_check_w_dict.inputs.root_file }}::num_warnings: ${{ steps.fine_spell_check_w_dict.outputs.num_warnings }}"; exit 1;'
+              run: 'echo "::error file=test/fine.tex::num_warnings: ${{ steps.fine_spell_check_w_dict.outputs.num_warnings }}"; exit 1;'
