Add test step with deployed image; closes #58 (#59)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -59,3 +59,14 @@ jobs:
             - name: Assert num_warnings == 0
               if: ${{ steps.fine_spell_check_w_dict.outputs.num_warnings != 0 }}
               run: 'echo "::error file=test/fine.tex::num_warnings: ${{ steps.fine_spell_check_w_dict.outputs.num_warnings }}"; exit 1;'
+            - name: Lint fine.tex with deployed action
+              id: fine_deployed
+              uses: ./
+              with:
+                  root_file: fine.tex
+                  working_directory: test/
+                  args: --check en --dict en.dict
+                  threshold_error: 0
+            - name: Assert num_warnings == 0
+              if: ${{ steps.fine_deployed.outputs.num_warnings != 0 }}
+              run: 'echo "::error file=test/fine.tex::num_warnings: ${{ steps.fine_deployed.outputs.num_warnings }}"; exit 1;'
