Use unknown word for spell check test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -37,18 +37,18 @@ jobs:
             - name: Assert num_warnings <= 21
               if: ${{ steps.bad_known_threshold.outputs.num_warnings > 21 }}
               run: 'echo "::error file=test/bad.tex::num_warnings: ${{ steps.bad_known_threshold.outputs.num_warnings }}"; exit 1;'
-            - name: Lint and spell-check fine.tex
+            - name: Lint and spell-check fine.tex without dict
+              id: fine_spell_check_wo_dict
               uses: ./
-              id: fine_spell_check
               with:
                   root_file: fine.tex
                   working_directory: test/
                   args: --check en
-                  threshold_error: 0
-            - name: Assert num_warnings == 0
-              if: ${{ steps.fine_spell_check.outputs.num_warnings != 0 }}
-              run: 'echo "::error file=test/fine.tex::num_warnings: ${{ steps.fine_spell_check.outputs.num_warnings }}"; exit 1;'
-            - name: Lint and spell-check fine.tex
+                  threshold_error: 1
+            - name: Assert num_warnings == 1
+              if: ${{ steps.fine_spell_check_wo_dict.outputs.num_warnings != 1 }}
+              run: 'echo "::error file=test/fine.tex::num_warnings: ${{ steps.fine_spell_check_wo_dict.outputs.num_warnings }}"; exit 1;'
+            - name: Lint and spell-check fine.tex with dict
               id: fine_spell_check_w_dict
               uses: ./
               with:
